version: '3'
services:
  web:
    environment:
      - CHOKIDAR_USEPOLLING=true 
      #when running react on windows, sometimes it
      #doesn't reload automatically after code change
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:/app #with this we could remove copy . . from dockerfile, but instructor prefers to keep
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    command: ["npm", "run", "test"]